-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://github.com/pgadmin-org/pgadmin4/issues/new/choose if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE IF NOT EXISTS epic_events.clients
(
    id serial NOT NULL,
    name_client character varying COLLATE pg_catalog."default",
    email character varying COLLATE pg_catalog."default",
    phone character varying COLLATE pg_catalog."default",
    creation_date date,
    update_date date,
    company_id integer,
    commercial_id integer,
    CONSTRAINT clients_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS epic_events.collaborators
(
    id serial NOT NULL,
    name_collaborator character varying COLLATE pg_catalog."default",
    contact character varying COLLATE pg_catalog."default",
    password_hash character varying COLLATE pg_catalog."default",
    department_id integer,
    CONSTRAINT collaborators_pkey PRIMARY KEY (id),
    CONSTRAINT collaborators_name_collaborator_key UNIQUE (name_collaborator)
);

CREATE TABLE IF NOT EXISTS epic_events.companies
(
    id serial NOT NULL,
    name_company character varying COLLATE pg_catalog."default",
    CONSTRAINT companies_pkey PRIMARY KEY (id),
    CONSTRAINT companies_name_company_key UNIQUE (name_company)
);

CREATE TABLE IF NOT EXISTS epic_events.contracts
(
    id serial NOT NULL,
    client_id integer,
    total_amount integer,
    remaining_amount integer,
    creation_date date,
    status boolean,
    CONSTRAINT contracts_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS epic_events.departments
(
    id serial NOT NULL,
    name_department character varying COLLATE pg_catalog."default",
    CONSTRAINT departments_pkey PRIMARY KEY (id),
    CONSTRAINT departments_name_department_key UNIQUE (name_department)
);

CREATE TABLE IF NOT EXISTS epic_events.events
(
    id serial NOT NULL,
    event_name character varying COLLATE pg_catalog."default",
    contract_id integer,
    support_id integer,
    location character varying COLLATE pg_catalog."default",
    participants integer,
    notes character varying COLLATE pg_catalog."default",
    start_date date,
    end_date date,
    CONSTRAINT events_pkey PRIMARY KEY (id)
);

ALTER TABLE IF EXISTS epic_events.clients
    ADD CONSTRAINT clients_commercial_id_fkey FOREIGN KEY (commercial_id)
    REFERENCES epic_events.collaborators (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS epic_events.clients
    ADD CONSTRAINT clients_company_id_fkey FOREIGN KEY (company_id)
    REFERENCES epic_events.companies (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS epic_events.collaborators
    ADD CONSTRAINT collaborators_department_id_fkey FOREIGN KEY (department_id)
    REFERENCES epic_events.departments (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS epic_events.contracts
    ADD CONSTRAINT contracts_client_id_fkey FOREIGN KEY (client_id)
    REFERENCES epic_events.clients (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS epic_events.events
    ADD CONSTRAINT events_contract_id_fkey FOREIGN KEY (contract_id)
    REFERENCES epic_events.contracts (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS epic_events.events
    ADD CONSTRAINT events_support_id_fkey FOREIGN KEY (support_id)
    REFERENCES epic_events.collaborators (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;

END;